config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #DSL - domain specific language ;; it is just ruby wrtten in a special way for a special purpose (routes in this case)
  resources :questions do
    resources :answers, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
    resources :votes, only: [:create, :update, :destroy]
  end

  resources :users, only: [:new, :create]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  get "/home" => "welcome#index"
  get "/about" => "welcome#about_me", as: :about_us
  get "/contact" => "contact#new", as: :new_contact
  post "/contact" => "contact#create", as: :contact

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :questions, only: [:index, :show, :create]
    end
  end

  # get "/questions/new" => "questions#new",    as: :new_question
  # post "/questions"    => "questions#create", as: :questions
  # get "/questions/:id" => "questions#show",   as: :question
  # get "/questions"     => "questions#index"
  # get "/questions/:id/edit" => "questions#edit", as: :edit_question
  # patch "/questions/:id" => "questions#update"
  # delete "/questions/:id" => "questions#destroy"

  root "welcome#index" #this defines get "/" as the main landing page!
end

app/models/question.rb
class Question < ApplicationRecord
  #this was added and associates the question with answer in a one to many fashion and provide handy methods to create associated answers
  has_many :answers, dependent: :destroy
  has_many :likes, dependent: :destroy

  belongs_to :user
  has_many :users, through: :likes

  # validates(:title, {presence: true})
  validates :title, presence: true, uniqueness: {message: "must be unique!"}
  validates :body, presence: true, length: {minimum: 5}
  has_many :votes, dependent: :destroy
  has_many :voting_users, through: :votes, source: :user

  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  extend FriendlyId
  friendly_id :title, use: [:slugged, :history]
  mount_uploader :image, ImageUploader

  # This validatse that the title/body combination is unique which means that
  # title doesn't have to be unique by itself, body doesn't have to be unique
  # by itself but the combination of the two must be unique.
  # validates :body, uniqueness: {scope: :title}

  # VALID_EMAIL_REGEX = /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  # validates :email, format: VALID_EMAIL_REGEX

  # this defines a custom validation. It takes a first argument which in this
  # case is a private method
  validate :no_monkey

  # after_initialize :set_defaults

  before_validation :capitalize_title

  def titleized_title
    title.titleize
  end

  # scope :recent_ten, lambda { order(created_at: :desc).limit(10) }
  def self.recent_ten
    order(created_at: :desc).limit(10)
  end
# searches keyword wildcard in title and body. be mindful of array syntax
  def self.search(keyword)
    where(["title ILIKE ? OR body ILIKE ?", "%#{keyword}%", "%#{keyword}%"])
  end

  def like_for(user)
    likes.find_by_user_id(user)
  end

  def vote_for(user)
    votes.find_by_user_id user
  end

  def vote_value
    votes.where(is_up: true).count - votes.where(is_up:false).count
  end



  delegate :first_name, :last_name, to: :user, prefix: true, allow_nil: true
  # #top line replaces below methods when calling json API, so above line will be user_first_name as method 
  # def user_first_name
  #   user.first_name if user
  #   # if user is needed because some users are deleted and nil. need if otherwise exception error!!
  # end
  #
  # def user_last_name
  #   user.last_name if user
  # end

  private
# conditional is needed to check that title exists and not null, otherwise error will occur when trying to capitalize
  def capitalize_title
    self.title.capitalize! if title
  end

  def no_monkey
    if title && title.downcase.include?("monkey")
      errors.add(:title, "No monkey please!")
    end
  end

  # def set_defaults
  #   self.view_count ||= 0
  # end


end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::BaseController

  before_action :authenticate_api_user

  QUESTIONS_PER_PAGE = 10
  def index
    @questions = Question.order(created_at: :desc).page(params[:page]).per(QUESTIONS_PER_PAGE)
    # render json: @questions
  end

  def show
    question = Question.friendly.find params[:id]
    render json: question
  end

  private

  def authenticate_api_user
    user = User.find_by_api_key params[:api_key]
    head :unauthorized unless user
  end

# API KEY GENERATION
# RAILS C > User.all.each {|x| x.send(:generate_api_key) & x.save}

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  #REFACTORING - this method occurs before the action is done and it is ideally private. to reduce repeition of code
  before_action :find_question, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:create, :edit, :destroy, :update, :new]
  before_action :authorize!, only: [:destroy, :update, :edit]

  def new
    @question = Question.new
  end

  def create
    # questions_params = params.require(:question).permit([:title,:body]) #refactored
    #{title: "salfsad", body: "alsdfj"} above is a strong parameter that allows mass-assigning the attributes that we want user to set
    @question = Question.new questions_params
    @question.user = current_user
    if @question.save
      # render :show
      flash[:notice] = "Question created successfully"
      redirect_to @question
    else
      render :new
    end
  end

  def show
    # @question = Question.find params[:id] #refactored
    @answer = Answer.new
  end

  def index
    @questions = Question.order(created_at: :desc).page(params[:page]).per(10)
    respond_to do |format|
      format.html {render}
      format.json {render json: @questions}
    end
  end

  def edit
    # @question = Question.find params[:id] #refactored
  end

  def update
  @question.slug = nil
  # @question = Question.find params[:id] #refactored
  if @question.update questions_params
    # params.require(:question).permit([:title, :body])
    redirect_to question_path(@question)
  else
    render :edit
  end
  end

  def destroy
    # question = Question.find params[:id] #not not due to refactoring
    @question.destroy # add a @ question
    redirect_to questions_path
  end

  private

  def find_question
    @question = Question.friendly.find params[:id]
  end

  def questions_params
        params.require(:question).permit([:title,:body, {tag_ids: []}])
  end

  def authorize!
        redirect_to root_path, alert: "access denied" unless @question.user == current_user
  end

    def user_vote
      @user_vote ||= @question.vote_for current_user
    end
    helper_method :user_vote
end

app/helpers/api/v1/questions_helper.rb
module Api::V1::QuestionsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%# form_for is a Rails built-in form helper which generates a form that integegrates
    nicely with a matching controller (in this case questions_controller).
   Case 1: if @question is not persisted (not yet saved to the database), then
           form_for will make the form send a `POST` request to `questions_path`
           which should be defined to submit to questions controller / create action.
           Also, if you have any attributes pre-set on any of the @question
           fields (such as title or body). it will be pre-populate those fields.
           One more thing, it will also add a special class if there happens to be
           errors on a specific field.
    Case 2: if @question is persisted (saved to the database), then
            form_for will make the form send a `PATCH` request to `question_path(@question)`
            which should be defined to submit to questions controller / update action.
            Also, if you have any attributes pre-set on any of the @question
            fields (such as title or body). it will be pre-populate those fields.
            One more thing, it will also add a special class if there happens to be
            errors on a specific field.
  %>


  <%#= @question.errors.full_messages.join(", ") %>
  <!-- installed simple gem -->
  <%= simple_form_for @question do |f| %>
    <div class = "form-group">
      <!-- <%= f.label :title %>
      <%= f.text_field :title, class: "form-control" %> -->
    <!-- </div> -->
    <%= f.input :title %>
    <!-- <div>
      <%= f.label :body %>
      <%= f.text_area :body, class: "form-control"  %>
    </div> -->
    <%= f.input :body %>
    <%= f.input :image %>
    <div>
      <%= f.collection_select(:tag_ids, Tag.all, :id, :name,
                              {},
                              { multiple: true, class: 'chosen-select form-control' }) %>
    </div>
    <div class = "form-group">
      <%= f.submit class: "btn btn-primary" %>
    </div>

  <% end %>

  <script>
    $(".chosen-select").chosen({});
  </script>

app/views/questions/_vote.html.erb
<% user_vote = @question.vote_for current_user %>

<% if user_vote.nil? %>
  <%= link_to 'Vote Up', question_votes_path(@question, vote: { is_up: true }),
                         method: :post,
                         remote: true %>
  <%= link_to 'Vote Down', question_votes_path(@question, vote: { is_up: false }),
                           method: :post %>
  (<%= @question.vote_value %>)
<% elsif user_vote.is_up %>
  <%= link_to 'Remove Vote Up', question_vote_path(@question, user_vote),
                                method: :delete,
                                remote: true %>
  <%= link_to "Switch to Vote Down", question_vote_path(@question, user_vote, vote: {is_up: false}), method: :patch, remote: true %>
  (<%= @question.vote_value %>)
<% else %>
  <%= link_to "Switch to Vote Up",
            question_vote_path(@question, user_vote, vote: { is_up: true }),
            method: :patch,
            remote: true %>
  <%= link_to 'Remove Vote Down', question_vote_path(@question, user_vote),
                                method: :delete %>
  (<%= @question.vote_value %>)
<% end %>

app/views/questions/edit.html.erb
<h1>Edit question</h1>
<%= render "form" %>
<!-- <%# #refactored the below form since it was duplicated with new.html.erb and edit.html.erb.
# the above code render will look for partial names '_form.html.erb' within the same folder as this file. to look at seperate path/folder list full path  %> -->

<%# form_for is a Rails built-in form helper which generates a form that integegrates
    nicely with a matching controller (in this case questions_controller).
    Case 1: if @question is not persisted (not yet saved to the database), then
            form_for will make the form send a `POST` request to `questions_path`
            which should be defined to submit to questions controller / create action.
            Also, if you have any attributes pre-set on any of the @question
            fields (such as title or body). it will be pre-populate those fields.
            One more thing, it will also add a special class if there happens to be
            errors on a specific field.
 %>

<!-- <% if @question.errors.any? %>
  <ul>
    <% @question.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %> -->
<!-- <%= @question.errors.full_messages.join(", ") %>
<%= form_for @question do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  <%= f.submit %>

<% end %> -->

app/views/questions/index.html.erb
<h1>All Questions</h1>

<% @questions.each do |q| %>
<%= link_to q.title, question_path(q) %>
<hr>
<% end %>

<%= paginate @questions %>

app/views/questions/new.html.erb
<h1>New Question</h1>
<%= render "form" %>
<!-- <%# #refactored the below form since it was duplicated with new.html.erb and edit.html.erb.
# the above code render will look for partial names '_form.html.erb' within the same folder as this file. to look at seperate path/folder list full path  %> -->
<%# form_for is a Rails built-in form helper which generates a form that integegrates
    nicely with a matching controller (in this case questions_controller).
    Case 1: if @question is not persisted (not yet saved to the database), then
            form_for will make the form send a `POST` request to `questions_path`
            which should be defined to submit to questions controller / create action.
            Also, if you have any attributes pre-set on any of the @question
            fields (such as title or body). it will be pre-populate those fields.
            One more thing, it will also add a special class if there happens to be
            errors on a specific field.
 %>

<!-- <% if @question.errors.any? %>
  <ul>
    <% @question.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %> -->

<!-- <%= @question.errors.full_messages.join(", ") %>
<%= form_for @question do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  <%= f.submit %>

<% end %> -->

app/views/questions/show.html.erb
<h1>
    <%= @question.title %></h1>
<p>

    <%= @question.body %>
</p>
<p>
   <%= @question.tags.map {|t| t.name }.join(", ") %>
</p>
<%= link_to "Edit", edit_question_path(@question) %>
<%= link_to "Delete", question_path(@question),
                      method: :delete,
                      data: {confirm: "Are you sure?"} %>
<hr />

<% user_like = @question.like_for(current_user) %>
<% if user_like.present? %>
<%= link_to "Un-Like", question_like_path(@question, user_like), method: :delete %>
 <% else %>
 <%= link_to "Like", question_likes_path(@question), method: :post %>
 <% end %>
 (<%= pluralize @question.likes.count, "like" %>)
 <hr />

<div id = "vote">
  <%= render "vote" %>
</div>

<!-- NEW ANSWER FORM WITH AJAX -->
<%= @answer.errors.full_messages.join(", ")  %>
<%= form_for [@question, @answer], remote: true do |f| %>
  <div>
    <%= f.text_area :body %>
  </div>
  <%= f.submit %>
<% end %>


 <hr />


 <h2>Answers</h2>
 <div id="answers">
   <% @question.answers.each do |ans| %>
     <%= render "/answers/answer", answer: ans %>
   <hr />
 <% end %>
 </div>
 <!-- <hr />
 <%# end %> -->